services:
  shelfmark-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: shelfmark-lite
    container_name: shelfmark-dev
    ports:
      - 8085:8084
    environment:
      DEBUG: "true"
      FLASK_PORT: 8084
      PUID: 1000
      PGID: 1000
    volumes:
      - ./.local/config:/config
      - /home/blickysparqo/homelab/data/books:/books
      - ./.local/log:/var/log/shelfmark
      - ./.local/tmp:/tmp/shelfmark
    networks:
      - homelab_homelab

networks:
  homelab_homelab:
    external: true